name: Release
on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
env:
  IMAGE_NAME: argocd
  REGISTRY: quay.io/syself
  metadata_flavor: latest=true
  metadata_tags: type=ref,event=tag

jobs:
  argocd-image:
    name: Build and push argocd image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Generate metadata
        id: meta
        uses: ./.github/actions/metadata
        with:
          quay_username: ${{ secrets.QUAY_USERNAME }}
          metadata_flavor: ${{ env.metadata_flavor }}
          metadata_tags: ${{ env.metadata_tags }}

      - name: Log into quay.io
        uses: docker/login-action@v2
        env:
          QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
        if: ${{ env.QUAY_USERNAME != '' }}
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Build and push argocd image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha, scope=${{ github.workflow }}
          cache-to: type=gha, mode=max, scope=${{ github.workflow }}
  release:
    name: Create draft release
    runs-on: ubuntu-latest
    needs:
      - argocd-image
    steps:
      - name: Set env
        run: echo "RELEASE_TAG=${GITHUB_REF:10}" >> $GITHUB_ENV
      - name: checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install go
        uses: actions/setup-go@v4
        with:
          go-version: "^1.19"
      - name: generate release notes
        run: |
          make release-notes
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: out/*
          body_path: _releasenotes/${{ env.RELEASE_TAG }}.md
